const STATIX_PREFIX = "statix";

export default {
	STATIX_PREFIX,
	RENDER_PHASE_NAMES: {
		0: "INIT",
		1: "IDLE",
		2: "MOUNT",
		3: "UNMOUNT",
		4: "RENDERING"
	},
	HTML_DATASET_NAMES: {
		ID:          `${STATIX_PREFIX}-id`,
		BIND:        `${STATIX_PREFIX}-bind`,
		ACTION:      `${STATIX_PREFIX}-action`,
		PLACEHOLDER: `${STATIX_PREFIX}-placeholder`
	},
	JS_DATASET_NAMES: {
		ID:          `${STATIX_PREFIX}Id`,
		BIND:        `${STATIX_PREFIX}Bind`,
		ACTION:      `${STATIX_PREFIX}Action`,
		PLACEHOLDER: `${STATIX_PREFIX}Placeholder`
	},
	TYPE_NAMES: {
		STATIX_ELEMENT: "StatixElement",
		STATIX_DOM:     "StatixDOM",
		STATIX_SIGNAL:  "StatixSignal",
		STRING:         "String",
		ARRAY:          "Array",
		NUMBER:         "Number",
		BOOLEAN:        "Boolean",
		UNDEFINED:      "Undefined",
		NULL:           "Null",
		ANY:            "Any",
		OBJECT:         "Object",
		SYMBOL:         "Symbol",
		FUNCTION:       "Function",
		HTML_ELEMENT:   "HTMLElement",
		HTML_FRAGMENT:  "DocumentFragment",
		HTML_TEXT_NODE: "TextNode",
	},
	EVENT_NAMES: [
		"onwheel",
		"onclick",
		"ondblclick",
		"onerror",
		"onfocus",
		"onfocusin",
		"onkeydown",
		"onkeypress",
		"onkeyup",
		"onload",
		"onloadeddata",
		"onloadedmetadata",
		"onloadstart",
		"onfocusout",
		"onmousedown",
		"onmouseenter",
		"onmouseleave",
		"onmousemove",
		"onmouseout",
		"onmouseover",
		"onmouseup",
		"onscroll",
		"onscrollend",
		"ontouchcancel",
		"ontouchend",
		"ontouchmove",
		"ontouchstart",

		// "onabort",
		// "onanimationcancel",
		// "onanimationend",
		// "onanimationiteration",
		// "onanimationstart",
		// "onauxclick",
		// "onbeforeinput",
		// "onbeforetoggle",
		// "oncancel",
		// "onblur",
		// "oncanplay",
		// "oncanplaythrough",
		// "onchange",
		// "onclose",
		// "oncompositionend",
		// "oncompositionstart",
		// "oncompositionupdate",
		// "oncontextlost",
		// "oncontextmenu",
		// "oncontextrestored",
		// "oncopy",
		// "oncuechange",
		// "oncut",
		// "ondrag",
		// "ondragend",
		// "ondragenter",
		// "ondragleave",
		// "ondragover",
		// "ondragstart",
		// "ondrop",
		// "ondurationchange",
		// "onemptied",
		// "onended",
		// "onformdata",
		// "ongotpointercapture",,
		// "oninput",
		// "oninvalid",
		// "onlostpointercapture",
		// "onpaste",
		// "onpause",
		// "onplay",
		// "onplaying",
		// "onpointercancel",
		// "onpointerdown",
		// "onpointerenter",
		// "onpointerleave",
		// "onpointermove",
		// "onpointerout",
		// "onpointerover",
		// "onpointerup",
		// "onprogress",
		// "onratechange",
		// "onreset",
		// "onresize",
		// "onsecuritypolicyviolation",
		// "onseeked",
		// "onseeking",
		// "onselect",
		// "onselectionchange",
		// "onselectstart",
		// "onslotchange",
		// "onstalled",
		// "onsubmit",
		// "onsuspend",
		// "ontimeupdate",
		// "ontoggle",
		// "ontransitioncancel",
		// "ontransitionend",
		// "ontransitionrun",
		// "ontransitionstart",
		// "onvolumechange",
		// "onwaiting",
		// "onwebkitanimationend",
		// "onwebkitanimationiteration",
		// "onwebkitanimationstart",
		// "onwebkittransitionend",
	]
};